// app/layout.tsx
import Link from 'next/link';
import './App.css';

export const metadata = {
  title: 'Next.js App',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-50">
        <nav className="bg-blue-800 text-white p-4">
          <ul className="flex space-x-8 justify-center">
            <li>
              <Link href="/" className="hover:text-blue-300">Home</Link>
            </li>
            <li>
              <Link href="/books" className="hover:text-blue-300">Books</Link>
            </li>
            <li>
              <Link href="/authors" className="hover:text-blue-300">Authors</Link>
            </li>
          </ul>
        </nav>
        <main className="p-6">{children}</main>
      </body>
    </html>
  );
}
